# Generated by Django 5.1.3 on 2025-11-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajador', models.CharField(max_length=200, verbose_name='Nombre del Trabajador')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Mensual')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('temporal', 'Temporal')], default='tiempo_completo', max_length=15, verbose_name='Tipo de Contrato')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Mano de Obra',
                'verbose_name_plural': 'Mano de Obra',
                'ordering': ['-creado_en'],
            },
        ),
    ]
