# Generated by Django 5.1.3 on 2025-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('mantenimiento', 'Mantenimiento'), ('depreciacion', 'Depreciación'), ('seguro', 'Seguros'), ('otros', 'Otros')], default='servicios', max_length=15, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Costo Indirecto de Fabricación',
                'verbose_name_plural': 'Costos Indirectos de Fabricación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
