# Generated by Django 5.1.3 on 2025-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_costoindirecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('juan_perez', 'Juan Pérez'), ('maria_garcia', 'María García'), ('carlos_lopez', 'Carlos López'), ('ana_martinez', 'Ana Martínez')], default='juan_perez', max_length=15, verbose_name='Nombre')),
                ('puesto', models.CharField(choices=[('contador', 'Contador'), ('operario', 'Operario'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente'), ('asistente', 'Asistente')], default='contador', max_length=15, verbose_name='Puesto')),
                ('antiguedad', models.CharField(choices=[('1-3', '1-3 años'), ('3-10', '3-10 años'), ('10+', '+10 años')], default='1-3', max_length=5, verbose_name='Antigüedad')),
                ('salario_nominal_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Nominal Mensual')),
                ('dias_trabajados', models.PositiveIntegerField(default=30, verbose_name='Días Trabajados')),
                ('sueldo_nominal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo Nominal')),
                ('costo_semana_salarial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Semana Salarial')),
                ('septimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Séptimo')),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacaciones')),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aguinaldo')),
                ('calculo_salario_cancelado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cálculo Salarial Cancelado')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
