# Generated by Django 5.1.3 on 2025-11-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='afp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AFP'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='incaf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INCAF'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='isss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ISSS'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='salario_total_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SALARIO TOTAL MENSUAL'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='salario_total_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SALARIO TOTAL SEMANAL'),
        ),
    ]
