# Generated by Django 5.1.3 on 2025-11-02 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='contabilizado', max_length=20)),
                ('tiene_iva', models.BooleanField(default=False)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('es_cuenta_detalle', models.BooleanField(default=True)),
                ('acepta_iva', models.BooleanField(default=False)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='contabilidad.cuenta')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('es_iva', models.BooleanField(default=False)),
                ('monto_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidad.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabilidad.cuenta')),
            ],
            options={
                'ordering': ['-asiento__fecha', 'id'],
            },
        ),
    ]
