# Generated by Django 5.2.7 on 2025-11-01 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_cuenta_options_asiento_numero_asiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['-asiento__fecha', 'id']},
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='numero_asiento',
        ),
        migrations.AddField(
            model_name='asiento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado'), ('anulado', 'Anulado')], default='contabilizado', max_length=20),
        ),
        migrations.AddField(
            model_name='asiento',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asiento',
            name='tiene_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='acepta_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='es_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partida',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partida',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
