# Generated by Django 5.1.3 on 2025-11-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_licencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='precio_venta',
        ),
    ]
