# Generated by Django 5.1.3 on 2025-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_remove_licencia_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='valor_total_inventario_db',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total Inventario'),
        ),
    ]
