# Generated by Django 5.2.7 on 2025-11-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_asiento_options_alter_partida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
